INSERT INTO `tags` (`Label`, Path)
VALUES ('c sharp', '/languages/Csharp-icon.png'),
       ('cpp', '/languages/C++-icon.png'),
       ('c', '/languages/C-icon.png'),
       ('css', '/languages/CSS-icon.png'),
       ('go', '/languages/GOLANG-icon.png'),
       ('html', '/languages/HTML-icon.png'),
       ('java', '/languages/JAVA-icon.png'),
       ('js', '/languages/JS-icon.png'),
       ('kotlin', '/languages/KOTLIN-icon.png'),
       ('php', '/languages/PHP-icon.png'),
       ('python', '/languages/PYTHON-icon.png'),
       ('r', '/languages/R-icon.png'),
       ('ruby', '/languages/RUBY-icon.png'),
       ('sql', '/languages/SQL-icon.png');