<<<<<<< HEAD
INSERT INTO `topics` (Title, Id_Status, Id_User)
VALUES ('carrouselsJs', 1, 1),
       ('responsive', 1, 1),
        ('animationsCss', 1, 1),
        ('darkMode', 1, 1),
        ('formValidation', 1, 1),
        ('apiIntegration', 1, 1),
        ('singlePageApplications', 1, 1),
       ('progressiveWebApps', 1, 1),
        ('serverSideRendering', 1, 1),
        ('lazyLoading', 1, 1),
        ('webSockets', 1, 1),
        ('contentManagement', 1, 1),
        ('searchEngineOptimization', 1, 1),
        ('webAccessibility', 1, 1),
        ('crossBrowserCompatibility', 1, 1),
        ('performanceOptimization', 1, 1),
        ('microservices', 1, 1),
        ('unitTesting', 1, 1),
        ('endToEndTesting', 1, 1),
        ('databaseDesign', 1, 1),
        ('versionControl', 1, 1);
