INSERT INTO posts (Title, Content, Id_topics, Id_User, Create_post)
VALUES
    -- Posts for topic 1: carrouselsJs
    ('Faut mieux faire un carrousel en natif ou avec bibliothèque ?',
     'Je suis en train de faire une boutique en js et je veux faire un carrousel pour afficher mes articles et j\'essaye de bien opti mon code donc je ne sais pas si je dois me faciliter la vie en utilisant swiper par exemple mais donc importer toutes une bibliothèque où me complexifier la vie en créant ma fonction qui fait le carrousel',
     1, 1, '2024-04-03'),
    ('Quelle bibliothèque de carrousel JavaScript recommandez-vous ?',
     'Je cherche une bibliothèque JavaScript légère pour créer un carrousel performant sur mon site web. Des recommandations ?',
     1, 2, '2024-04-04'),
    ('Comment optimiser les carrousels pour le SEO ?',
     'Quels sont les aspects à considérer pour s\'assurer que les carrousels JavaScript ne nuisent pas au référencement SEO de mon site ?',
     1, 3, '2024-04-05'),
    ('Les meilleures pratiques pour les carrousels en JavaScript',
     'Quelles sont les meilleures pratiques pour créer des carrousels fluides et performants en JavaScript ?',
     1, 4, '2024-04-06'),
    ('Gérer la compatibilité des carrousels JavaScript sur mobile',
     'Comment assurer que mon carrousel JavaScript fonctionne bien sur les appareils mobiles ?',
     1, 5, '2024-04-07'),
    ('Les erreurs courantes lors de la création de carrousels en JavaScript',
     'Quelles sont les erreurs courantes à éviter lors de la création de carrousels en JavaScript ?',
     1, 6, '2024-04-08'),
    ('Carrousels JavaScript et accessibilité',
     'Comment rendre les carrousels JavaScript accessibles pour les utilisateurs ayant des handicaps ?',
     1, 7, '2024-04-09'),
    ('Utilisation de carrousels pour afficher des produits',
     'Quels sont les avantages d\'utiliser un carrousel pour afficher des produits sur une boutique en ligne ?',
     1, 1, '2024-04-10'),
    ('Personnalisation de carrousels avec JavaScript',
     'Comment personnaliser les carrousels JavaScript pour qu\'ils s\'adaptent à mon thème de site web ?',
     1, 2, '2024-04-11'),
    ('Carrousels JavaScript et performances',
     'Comment optimiser les performances des carrousels JavaScript pour qu\'ils se chargent rapidement ?',
     1, 3, '2024-04-12'),
    ('Les meilleurs plugins de carrousel pour JavaScript en 2024',
     'Quels sont les plugins de carrousel JavaScript les plus recommandés en 2024 ?',
     1, 4, '2024-04-13'),
    ('Intégration de carrousels JavaScript dans un site WordPress',
     'Quelles sont les étapes pour intégrer un carrousel JavaScript dans un site WordPress ?',
     1, 5, '2024-04-14'),
    ('Alternatives aux carrousels JavaScript',
     'Quelles sont les alternatives aux carrousels JavaScript pour afficher du contenu de manière interactive ?',
     1, 6, '2024-04-15'),
    ('Troubleshooting des carrousels JavaScript',
     'Comment dépanner et résoudre les problèmes courants avec les carrousels JavaScript ?',
     1, 7, '2024-04-16'),
    ('Carrousels JavaScript pour les débutants',
     'Quels sont les conseils pour les débutants qui souhaitent créer leur premier carrousel en JavaScript ?',
     1, 1, '2024-04-17'),

    -- Posts for topic 2: responsive
    ('Comment gérer les points de rupture pour un site responsive ?',
     'Quels sont les points de rupture standards à utiliser pour un site web réactif et comment les gérer efficacement ?',
     2, 2, '2024-04-04'),
    ('Meilleures pratiques pour le design responsive',
     'Quelles sont les meilleures pratiques pour créer un design responsive qui fonctionne sur tous les appareils ?',
     2, 3, '2024-04-05'),
    ('Frameworks CSS pour un design responsive',
     'Quels sont les meilleurs frameworks CSS à utiliser pour un design responsive ?',
     2, 4, '2024-04-06'),
    ('Test de la réactivité d\'un site web',
     'Quels outils recommandez-vous pour tester la réactivité d\'un site web sur différents appareils ?',
     2, 5, '2024-04-07'),
    ('Fluidité du design responsive',
     'Comment s\'assurer que le design responsive de mon site est fluide et sans ruptures ?',
     2, 6, '2024-04-08'),
    ('Optimisation des images pour un site responsive',
     'Quelles techniques utiliser pour optimiser les images sur un site responsive ?',
     2, 7, '2024-04-09'),
    ('Grilles CSS pour un design responsive',
     'Comment utiliser les grilles CSS pour créer un design responsive efficace ?',
     2, 1, '2024-04-10'),
    ('Responsive design et SEO',
     'Comment le responsive design impacte-t-il le SEO de votre site web ?',
     2, 2, '2024-04-11'),
    ('Approches pour le design mobile-first',
     'Quels sont les avantages de l\'approche mobile-first pour le design responsive ?',
     2, 3, '2024-04-12'),
    ('Gestion des polices dans un design responsive',
     'Comment gérer les tailles de polices dans un design responsive pour garantir la lisibilité sur tous les appareils ?',
     2, 4, '2024-04-13'),
    ('Utilisation de media queries pour un design responsive',
     'Comment utiliser efficacement les media queries pour créer un design responsive ?',
     2, 5, '2024-04-14'),
    ('CSS Grid vs Flexbox pour un design responsive',
     'Quel est le meilleur choix entre CSS Grid et Flexbox pour un design responsive et pourquoi ?',
     2, 6, '2024-04-15'),
    ('Défis du design responsive et comment les surmonter',
     'Quels sont les principaux défis du design responsive et comment les surmonter ?',
     2, 7, '2024-04-16'),
    ('Compatibilité des navigateurs et design responsive',
     'Comment s\'assurer que le design responsive de votre site est compatible avec tous les navigateurs ?',
     2, 1, '2024-04-17'),
    ('Utilisation de frameworks JavaScript pour un design responsive',
     'Quels frameworks JavaScript sont recommandés pour améliorer un design responsive ?',
     2, 2, '2024-04-18'),

    -- Posts for topic 3: animationsCss
    ('Les meilleures pratiques pour les animations CSS ?',
     'Quelles sont les meilleures pratiques pour créer des animations fluides et performantes en CSS ?',
     3, 4, '2024-04-05'),
    ('Introduction aux animations CSS',
     'Comment démarrer avec les animations CSS pour ajouter des effets visuels à votre site web ?',
     3, 5, '2024-04-06'),
    ('Animations CSS et performances web',
     'Comment optimiser les animations CSS pour qu\'elles n\'impactent pas négativement les performances de votre site web ?',
     3, 6, '2024-04-07'),
    ('Utilisation des keyframes en CSS',
     'Comment utiliser les keyframes en CSS pour créer des animations complexes ?',
     3, 7, '2024-04-08'),
    ('CSS transitions vs animations',
     'Quand utiliser les transitions CSS par rapport aux animations CSS pour obtenir les meilleurs résultats ?',
     3, 1, '2024-04-09'),
    ('Animations CSS et accessibilité',
     'Comment s\'assurer que les animations CSS n\'entravent pas l\'accessibilité de votre site web ?',
     3, 2, '2024-04-10'),
    ('Les effets de hover en CSS',
     'Quels sont les effets de hover en CSS les plus populaires et comment les implémenter ?',
     3, 3, '2024-04-11'),
    ('Animations CSS pour les boutons',
     'Quelles sont les meilleures pratiques pour ajouter des animations CSS aux boutons de votre site web ?',
     3, 4, '2024-04-12'),
    ('Animations CSS et JavaScript',
     'Comment combiner CSS et JavaScript pour créer des animations plus interactives et dynamiques ?',
     3, 5, '2024-04-13'),
    ('Utilisation des préprocesseurs CSS pour les animations',
     'Comment les préprocesseurs CSS comme Sass ou LESS peuvent-ils simplifier la création d\'animations CSS ?',
     3, 6, '2024-04-14'),
    ('Animations CSS et compatibilité des navigateurs',
     'Comment s\'assurer que vos animations CSS sont compatibles avec tous les navigateurs ?',
     3, 7, '2024-04-15'),
    ('Les outils pour créer des animations CSS',
     'Quels outils recommandez-vous pour faciliter la création d\'animations CSS ?',
     3, 1, '2024-04-16'),
    ('Animations CSS pour le défilement',
     'Comment ajouter des animations CSS lors du défilement de la page pour améliorer l\'expérience utilisateur ?',
     3, 2, '2024-04-17'),
    ('Optimiser les animations CSS pour les appareils mobiles',
     'Quelles sont les meilleures pratiques pour optimiser les animations CSS pour les appareils mobiles ?',
     3, 3, '2024-04-18'),
    ('Exemples d\'animations CSS inspirantes',
     'Quels sont les exemples d\'animations CSS inspirantes que vous avez vus récemment et comment les recréer ?',
     3, 4, '2024-04-19'),

    -- Posts for topic 4: darkMode
    ('Avantages du mode sombre pour les utilisateurs',
     'Quels sont les avantages du mode sombre pour les utilisateurs et comment l\'implémenter efficacement sur un site web ?',
     4, 5, '2024-04-06'),
    ('Implémenter le mode sombre avec CSS variables',
     'Comment utiliser les variables CSS pour implémenter un mode sombre sur votre site web ?',
     4, 6, '2024-04-07'),
    ('Switch entre mode clair et mode sombre',
     'Quels sont les moyens les plus simples et efficaces pour permettre aux utilisateurs de passer du mode clair au mode sombre ?',
     4, 7, '2024-04-08'),
    ('Le mode sombre et la consommation d\'énergie',
     'Comment le mode sombre peut-il aider à réduire la consommation d\'énergie des appareils ?',
     4, 1, '2024-04-09'),
    ('Les meilleures pratiques pour le design en mode sombre',
     'Quelles sont les meilleures pratiques pour concevoir des interfaces utilisateur en mode sombre ?',
     4, 2, '2024-04-10'),
    ('Accessibilité du mode sombre',
     'Comment s\'assurer que le mode sombre reste accessible pour tous les utilisateurs, y compris ceux avec des déficiences visuelles ?',
     4, 3, '2024-04-11'),
    ('Mode sombre et branding',
     'Comment maintenir la cohérence de la marque lorsque vous implémentez un mode sombre sur votre site ?',
     4, 4, '2024-04-12'),
    ('Mode sombre automatique basé sur les préférences système',
     'Comment configurer votre site web pour qu\'il bascule automatiquement en mode sombre en fonction des préférences système de l\'utilisateur ?',
     4, 5, '2024-04-13'),
    ('Les défis du mode sombre',
     'Quels sont les défis courants lors de l\'implémentation du mode sombre et comment les surmonter ?',
     4, 6, '2024-04-14'),
    ('Mode sombre et expérience utilisateur',
     'Comment le mode sombre peut-il améliorer l\'expérience utilisateur et quelles sont les meilleures pratiques pour le mettre en place ?',
     4, 7, '2024-04-15'),
    ('Exemples de sites web avec un excellent mode sombre',
     'Quels sont les exemples de sites web avec un mode sombre bien implémenté et pourquoi sont-ils réussis ?',
     4, 1, '2024-04-16'),
    ('Impact du mode sombre sur la lisibilité',
     'Comment le mode sombre affecte-t-il la lisibilité du texte et quelles sont les solutions pour améliorer cela ?',
     4, 2, '2024-04-17'),
    ('Mode sombre et CSS media queries',
     'Comment utiliser les media queries CSS pour implémenter un mode sombre sur votre site web ?',
     4, 3, '2024-04-18'),
    ('Mode sombre et animations CSS',
     'Comment créer des animations CSS qui fonctionnent bien en mode sombre sans être distrayantes ?',
     4, 4, '2024-04-19'),
    ('Mode sombre pour les applications mobiles',
     'Quelles sont les considérations spécifiques pour implémenter un mode sombre dans les applications mobiles ?',
     4, 5, '2024-04-20'),

    -- Posts for topic 5: formValidation
    ('Validation des formulaires en JavaScript vs HTML5',
     'Quelle est la meilleure approche pour valider les formulaires, en utilisant JavaScript ou les attributs HTML5 ?',
     5, 6, '2024-04-07'),
    ('Les meilleures bibliothèques pour la validation de formulaires',
     'Quelles sont les bibliothèques JavaScript les plus efficaces pour la validation des formulaires ?',
     5, 7, '2024-04-08'),
    ('Validation de formulaire côté client vs côté serveur',
     'Quels sont les avantages et les inconvénients de la validation de formulaire côté client par rapport à la validation côté serveur ?',
     5, 1, '2024-04-09'),
    ('Validation des formulaires et accessibilité',
     'Comment rendre la validation des formulaires accessible aux utilisateurs ayant des déficiences ?',
     5, 2, '2024-04-10'),
    ('Gestion des erreurs de validation en temps réel',
     'Comment gérer et afficher les erreurs de validation des formulaires en temps réel pour une meilleure expérience utilisateur ?',
     5, 3, '2024-04-11'),
    ('Meilleures pratiques pour la validation des formulaires HTML5',
     'Quelles sont les meilleures pratiques pour tirer parti des fonctionnalités de validation intégrées dans HTML5 ?',
     5, 4, '2024-04-12'),
    ('Utilisation de regex pour la validation des formulaires',
     'Comment utiliser les expressions régulières (regex) pour valider les champs de formulaire de manière efficace ?',
     5, 5, '2024-04-13'),
    ('Validation des formulaires pour les données sensibles',
     'Quelles sont les considérations de sécurité à prendre en compte lors de la validation de formulaires contenant des données sensibles ?',
     5, 6, '2024-04-14'),
    ('Gestion des formulaires multi-étapes',
     'Comment gérer la validation des formulaires multi-étapes pour assurer une saisie correcte des données ?',
     5, 7, '2024-04-15'),
    ('Tests unitaires pour la validation des formulaires',
     'Comment écrire des tests unitaires pour s\'assurer que la validation des formulaires fonctionne correctement ?',
     5, 1, '2024-04-16'),
    ('Les erreurs de validation les plus courantes et comment les éviter',
     'Quelles sont les erreurs de validation de formulaire les plus courantes et comment les éviter ?',
     5, 2, '2024-04-17'),
    ('Validation conditionnelle des champs de formulaire',
     'Comment implémenter une validation conditionnelle pour certains champs de formulaire en fonction des saisies utilisateur ?',
     5, 3, '2024-04-18'),
    ('Expériences utilisateur optimales avec la validation de formulaires',
     'Quelles sont les meilleures pratiques pour offrir une expérience utilisateur optimale avec la validation de formulaires ?',
     5, 4, '2024-04-19'),
    ('Utilisation de bibliothèques de validation pour React',
     'Quelles sont les meilleures bibliothèques de validation de formulaires pour les applications React ?',
     5, 5, '2024-04-20'),

    -- Posts for topic 6: apiIntegration
    ('Intégration d\'API RESTful dans une application web',
     'Quelles sont les étapes pour intégrer une API RESTful dans une application web existante ?',
     6, 2, '2024-04-08'),
    ('Meilleures pratiques pour la sécurité des API',
     'Quelles sont les meilleures pratiques pour sécuriser une API et protéger les données sensibles ?',
     6, 3, '2024-04-09'),
    ('Gestion des erreurs lors de l\'appel d\'une API',
     'Comment gérer les erreurs et exceptions lors de l\'appel d\'une API dans votre application web ?',
     6, 4, '2024-04-10'),
    ('Documentation des API : pourquoi et comment',
     'Pourquoi est-il important de bien documenter votre API et comment le faire de manière efficace ?',
     6, 5, '2024-04-11'),
    ('Utilisation de GraphQL pour les API',
     'Quels sont les avantages de GraphQL par rapport aux API RESTful et comment l\'implémenter ?',
     6, 6, '2024-04-12'),
    ('Authentification et autorisation avec les API',
     'Quelles sont les meilleures pratiques pour gérer l\'authentification et l\'autorisation dans les API ?',
     6, 7, '2024-04-13'),
    ('Les outils pour tester les API',
     'Quels outils recommandez-vous pour tester les API et s\'assurer qu\'elles fonctionnent correctement ?',
     6, 1, '2024-04-14'),
    ('Les performances des API',
     'Comment optimiser les performances de votre API pour qu\'elle réponde rapidement aux requêtes ?',
     6, 2, '2024-04-15'),
    ('Les erreurs courantes lors de l\'intégration des API',
     'Quelles sont les erreurs courantes à éviter lors de l\'intégration d\'une API dans une application web ?',
     6, 3, '2024-04-16'),
    ('Versioning des API : pourquoi et comment le faire',
     'Pourquoi est-il important de versionner une API et comment le faire correctement ?',
     6, 4, '2024-04-17'),
    ('Intégration d\'API dans une application mobile',
     'Quelles sont les particularités de l\'intégration d\'API dans une application mobile par rapport à une application web ?',
     6, 5, '2024-04-18'),
    ('Les meilleures pratiques pour les requêtes API',
     'Quelles sont les meilleures pratiques pour envoyer des requêtes API et gérer les réponses de manière efficace ?',
     6, 6, '2024-04-19'),
    ('API Gateway : rôle et avantages',
     'Quel est le rôle d\'une API Gateway et quels sont ses avantages pour la gestion des API ?',
     6, 7, '2024-04-20'),
    ('Les outils de monitoring pour les API',
     'Quels outils recommandez-vous pour surveiller et analyser les performances des API ?',
     6, 1, '2024-04-21'),
    ('Les meilleures pratiques pour les microservices et les API',
     'Comment les microservices et les API peuvent-ils fonctionner ensemble pour créer une architecture efficace et scalable ?',
     6, 2, '2024-04-22'),

    -- Posts for topic 7: singlePageApplications
    ('Choisir le bon framework pour une Single Page Application',
     'Quels sont les critères pour choisir le bon framework (React, Vue, Angular) pour développer une Single Page Application ?',
     7, 4, '2024-04-09'),
    ('Performance des Single Page Applications',
     'Comment optimiser la performance de votre Single Page Application pour qu\'elle soit rapide et réactive ?',
     7, 5, '2024-04-10'),
    ('Gestion de l\'état dans les Single Page Applications',
     'Quelles sont les meilleures pratiques pour gérer l\'état de votre application dans une Single Page Application ?',
     7, 6, '2024-04-11'),
    ('SEO pour les Single Page Applications',
     'Comment améliorer le SEO de votre Single Page Application pour qu\'elle soit bien référencée par les moteurs de recherche ?',
     7, 7, '2024-04-12'),
    ('Routing dans les Single Page Applications',
     'Comment implémenter un système de routing efficace dans votre Single Page Application ?',
     7, 1, '2024-04-13'),
    ('Les erreurs courantes dans les Single Page Applications',
     'Quelles sont les erreurs courantes à éviter lors du développement de Single Page Applications ?',
     7, 2, '2024-04-14'),
    ('Les bibliothèques d\'animation pour les Single Page Applications',
     'Quelles sont les bibliothèques d\'animation recommandées pour les Single Page Applications et comment les intégrer ?',
     7, 3, '2024-04-15'),
    ('Test des Single Page Applications',
     'Quels sont les outils et les meilleures pratiques pour tester les Single Page Applications ?',
     7, 4, '2024-04-16'),
    ('Les avantages des Single Page Applications',
     'Quels sont les avantages des Single Page Applications par rapport aux applications multi-pages traditionnelles ?',
     7, 5, '2024-04-17'),
    ('Déploiement des Single Page Applications',
     'Quelles sont les meilleures pratiques pour déployer une Single Page Application sur un serveur de production ?',
     7, 6, '2024-04-18'),
    ('Intégration des API dans les Single Page Applications',
     'Comment intégrer efficacement les API dans une Single Page Application pour une interaction fluide avec le backend ?',
     7, 7, '2024-04-19'),
    ('Les défis des Single Page Applications',
     'Quels sont les défis courants lors du développement de Single Page Applications et comment les surmonter ?',
     7, 1, '2024-04-20'),
    ('Les meilleures pratiques pour les Single Page Applications',
     'Quelles sont les meilleures pratiques pour garantir la maintenabilité et la scalabilité des Single Page Applications ?',
     7, 2, '2024-04-21'),
    ('Les outils de développement pour les Single Page Applications',
     'Quels outils de développement recommandez-vous pour accélérer la création de Single Page Applications ?',
     7, 3, '2024-04-22'),
    ('Exemples de Single Page Applications réussies',
     'Quels sont les exemples de Single Page Applications bien conçues et pourquoi sont-elles réussies ?',
     7, 4, '2024-04-23'),

    -- Posts for topic 8: progressiveWebApps
    ('Les avantages des Progressive Web Apps',
     'Quels sont les avantages des Progressive Web Apps par rapport aux applications natives ?',
     8, 5, '2024-04-07'),
    ('Mise en cache et hors ligne dans les Progressive Web Apps',
     'Comment implémenter la mise en cache et la fonctionnalité hors ligne dans une Progressive Web App ?',
     8, 6, '2024-04-08'),
    ('Les meilleures pratiques pour développer une Progressive Web App',
     'Quelles sont les meilleures pratiques pour développer une Progressive Web App performante et fiable ?',
     8, 7, '2024-04-09'),
    ('Les outils pour tester et déboguer les Progressive Web Apps',
     'Quels outils recommandez-vous pour tester et déboguer les Progressive Web Apps ?',
     8, 1, '2024-04-10'),
    ('Les critères pour une bonne Progressive Web App',
     'Quels sont les critères à remplir pour qu\'une Progressive Web App soit considérée comme de haute qualité ?',
     8, 2, '2024-04-11'),
    ('Sécurité dans les Progressive Web Apps',
     'Comment assurer la sécurité de votre Progressive Web App contre les menaces courantes ?',
     8, 3, '2024-04-12'),
    ('Exemples de Progressive Web Apps réussies',
     'Quels sont les exemples de Progressive Web Apps bien conçues et pourquoi sont-elles réussies ?',
     8, 4, '2024-04-13'),
    ('Améliorer les performances des Progressive Web Apps',
     'Quelles sont les techniques pour améliorer les performances des Progressive Web Apps ?',
     8, 5, '2024-04-14'),
    ('Les manifestes et les Progressive Web Apps',
     'Comment configurer et utiliser les manifestes pour les Progressive Web Apps ?',
     8, 6, '2024-04-15'),
    ('Les Progressive Web Apps et le SEO',
     'Comment optimiser les Progressive Web Apps pour le SEO ?',
     8, 7, '2024-04-16'),
    ('Les API des Progressive Web Apps',
     'Quelles sont les principales API à utiliser pour tirer parti des fonctionnalités des Progressive Web Apps ?',
     8, 1, '2024-04-17'),
    ('Service Workers et Progressive Web Apps',
     'Quel est le rôle des Service Workers dans les Progressive Web Apps et comment les implémenter ?',
     8, 2, '2024-04-18'),
    ('Déploiement des Progressive Web Apps',
     'Quelles sont les meilleures pratiques pour déployer une Progressive Web App sur un serveur de production ?',
     8, 3, '2024-04-19'),
    ('Les Progressive Web Apps et l\'expérience utilisateur',
     'Comment les Progressive Web Apps peuvent-elles améliorer l\'expérience utilisateur par rapport aux applications web traditionnelles ?',
     8, 4, '2024-04-20'),

    -- Posts for topic 9: serverSideRendering
    ('Les avantages du rendu côté serveur',
     'Quels sont les avantages du rendu côté serveur (SSR) par rapport au rendu côté client ?',
     9, 7, '2024-04-08'),
    ('Mise en œuvre de Server-Side Rendering avec React',
     'Comment mettre en œuvre le Server-Side Rendering avec React pour améliorer les performances et le SEO ?',
     9, 1, '2024-04-09'),
    ('Les défis du rendu côté serveur',
     'Quels sont les défis courants lors de la mise en œuvre du rendu côté serveur et comment les surmonter ?',
     9, 2, '2024-04-10'),
    ('Server-Side Rendering vs Static Site Generation',
     'Quelle est la différence entre le rendu côté serveur et la génération de sites statiques, et quand utiliser chaque méthode ?',
     9, 3, '2024-04-11'),
    ('SEO et Server-Side Rendering',
     'Comment le Server-Side Rendering améliore-t-il le SEO par rapport au rendu côté client ?',
     9, 4, '2024-04-12'),
    ('Les frameworks pour le rendu côté serveur',
     'Quels sont les meilleurs frameworks pour implémenter le Server-Side Rendering dans une application web ?',
     9, 5, '2024-04-13'),
    ('Les performances du rendu côté serveur',
     'Comment optimiser les performances de votre application utilisant le rendu côté serveur ?',
     9, 6, '2024-04-14'),
    ('Les meilleures pratiques pour le rendu côté serveur',
     'Quelles sont les meilleures pratiques pour garantir une mise en œuvre réussie du rendu côté serveur ?',
     9, 7, '2024-04-15'),
    ('Intégration du Server-Side Rendering avec les API',
     'Comment intégrer efficacement le Server-Side Rendering avec les appels API pour une expérience utilisateur fluide ?',
     9, 1, '2024-04-16'),
    ('Les outils de débogage pour le rendu côté serveur',
     'Quels outils de débogage recommandez-vous pour les applications utilisant le Server-Side Rendering ?',
     9, 2, '2024-04-17'),
    ('Les erreurs courantes dans le rendu côté serveur',
     'Quelles sont les erreurs courantes à éviter lors de la mise en œuvre du Server-Side Rendering ?',
     9, 3, '2024-04-18'),
    ('Le Server-Side Rendering et la sécurité',
     'Comment assurer la sécurité de votre application web utilisant le Server-Side Rendering ?',
     9, 4, '2024-04-19'),
    ('Server-Side Rendering et mise en cache',
     'Quelles sont les stratégies de mise en cache à adopter pour améliorer les performances du Server-Side Rendering ?',
     9, 5, '2024-04-20'),

    -- Posts for topic 10: lazyLoading
    ('Les avantages du Lazy Loading',
     'Quels sont les avantages du Lazy Loading pour les performances de votre site web ?',
     10, 3, '2024-04-08'),
    ('Implémenter le Lazy Loading des images',
     'Comment implémenter le Lazy Loading pour les images sur votre site web pour améliorer le temps de chargement ?',
     10, 4, '2024-04-09'),
    ('Lazy Loading des composants dans React',
     'Comment utiliser le Lazy Loading pour les composants React afin d\'optimiser les performances ?',
     10, 5, '2024-04-10'),
    ('Lazy Loading et SEO',
     'Comment s\'assurer que le Lazy Loading n\'affecte pas négativement le SEO de votre site web ?',
     10, 6, '2024-04-11'),
    ('Les meilleures pratiques pour le Lazy Loading',
     'Quelles sont les meilleures pratiques pour implémenter efficacement le Lazy Loading dans vos projets web ?',
     10, 7, '2024-04-12'),
    ('Lazy Loading des vidéos',
     'Comment implémenter le Lazy Loading pour les vidéos sur votre site web pour améliorer les performances ?',
     10, 1, '2024-04-13'),
    ('Les outils et bibliothèques pour le Lazy Loading',
     'Quels outils et bibliothèques recommandez-vous pour faciliter l\'implémentation du Lazy Loading ?',
     10, 2, '2024-04-14'),
    ('Lazy Loading et compatibilité des navigateurs',
     'Comment gérer la compatibilité des navigateurs lors de l\'implémentation du Lazy Loading ?',
     10, 3, '2024-04-15'),
    ('Lazy Loading pour les sections de page',
     'Comment implémenter le Lazy Loading pour différentes sections de votre page web pour améliorer l\'expérience utilisateur ?',
     10, 4, '2024-04-16'),
    ('Les erreurs courantes dans le Lazy Loading',
     'Quelles sont les erreurs courantes à éviter lors de l\'implémentation du Lazy Loading ?',
     10, 5, '2024-04-17'),
    ('Les avantages du Lazy Loading pour les applications mobiles',
     'Comment le Lazy Loading peut-il améliorer les performances des applications mobiles ?',
     10, 6, '2024-04-18'),
    ('Lazy Loading pour les frameworks JavaScript',
     'Comment implémenter le Lazy Loading dans différents frameworks JavaScript (Vue, Angular, Svelte) ?',
     10, 7, '2024-04-19'),
    ('Lazy Loading et expérience utilisateur',
     'Comment le Lazy Loading peut-il améliorer l\'expérience utilisateur sur les sites web à contenu lourd ?',
     10, 1, '2024-04-20'),
    ('Lazy Loading des polices de caractères',
     'Comment implémenter le Lazy Loading pour les polices de caractères sur votre site web pour optimiser les performances ?',
     10, 2, '2024-04-21'),
    ('Lazy Loading et accessibilité',
     'Comment s\'assurer que le Lazy Loading n\'affecte pas négativement l\'accessibilité de votre site web ?',
     10, 3, '2024-04-22'),

    -- Posts for topic 11: webSockets
    ('Introduction aux WebSockets',
     'Qu\'est-ce que les WebSockets et comment fonctionnent-ils pour permettre une communication bidirectionnelle en temps réel ?',
     11, 5, '2024-04-08'),
    ('Les cas d\'utilisation des WebSockets',
     'Quels sont les principaux cas d\'utilisation des WebSockets dans les applications web modernes ?',
     11, 6, '2024-04-09'),
    ('Sécurité et WebSockets',
     'Quelles sont les considérations de sécurité à prendre en compte lors de l\'utilisation des WebSockets ?',
     11, 7, '2024-04-10'),
    ('Les performances des WebSockets',
     'Comment optimiser les performances de vos applications utilisant les WebSockets pour une communication fluide ?',
     11, 1, '2024-04-11'),
    ('WebSockets vs HTTP/2',
     'Quelle est la différence entre WebSockets et HTTP/2, et quand utiliser chaque technologie ?',
     11, 2, '2024-04-12'),
    ('Les meilleures pratiques pour les WebSockets',
     'Quelles sont les meilleures pratiques pour implémenter les WebSockets dans vos projets web ?',
     11, 3, '2024-04-13'),
    ('Les frameworks et bibliothèques pour les WebSockets',
     'Quels sont les frameworks et bibliothèques recommandés pour travailler avec les WebSockets ?',
     11, 4, '2024-04-14'),
    ('Les erreurs courantes avec les WebSockets',
     'Quelles sont les erreurs courantes à éviter lors de l\'implémentation des WebSockets dans vos applications ?',
     11, 5, '2024-04-15'),
    ('WebSockets et applications de chat en temps réel',
     'Comment utiliser les WebSockets pour créer des applications de chat en temps réel performantes ?',
     11, 6, '2024-04-16'),
    ('Les outils de débogage pour les WebSockets',
     'Quels outils recommandez-vous pour déboguer les applications utilisant les WebSockets ?',
     11, 7, '2024-04-17'),
    ('WebSockets et jeux en ligne',
     'Comment les WebSockets peuvent-ils être utilisés pour créer des jeux en ligne interactifs et réactifs ?',
     11, 1, '2024-04-18'),
    ('Les limites des WebSockets',
     'Quelles sont les limites des WebSockets et comment les surmonter dans vos projets ?',
     11, 2, '2024-04-19'),
    ('Les WebSockets et l\'Internet des objets (IoT)',
     'Comment utiliser les WebSockets pour permettre la communication en temps réel entre les appareils IoT ?',
     11, 3, '2024-04-20'),
    ('WebSockets et notifications en temps réel',
     'Comment implémenter des notifications en temps réel dans vos applications web avec les WebSockets ?',
     11, 4, '2024-04-21'),
    ('Les WebSockets et le streaming de données',
     'Comment les WebSockets peuvent-ils être utilisés pour le streaming de données en temps réel ?',
     11, 5, '2024-04-22'),

    -- Posts for topic 12: contentManagement
    ('Les systèmes de gestion de contenu populaires',
     'Quels sont les systèmes de gestion de contenu (CMS) les plus populaires et quels sont leurs avantages et inconvénients ?',
     12, 4, '2024-04-08'),
    ('Choisir un CMS pour votre site web',
     'Quels sont les critères à considérer lors du choix d\'un CMS pour votre site web ?',
     12, 5, '2024-04-09'),
    ('Personnalisation des CMS',
     'Comment personnaliser un CMS pour répondre aux besoins spécifiques de votre entreprise ?',
     12, 6, '2024-04-10'),
    ('Sécurité des systèmes de gestion de contenu',
     'Quelles sont les meilleures pratiques pour sécuriser votre CMS contre les cyberattaques ?',
     12, 7, '2024-04-11'),
    ('Optimisation des performances des CMS',
     'Comment optimiser les performances de votre site web basé sur un CMS ?',
     12, 1, '2024-04-12'),
    ('Les plugins et extensions pour CMS',
     'Quels sont les plugins et extensions incontournables pour améliorer les fonctionnalités de votre CMS ?',
     12, 2, '2024-04-13'),
    ('Les erreurs courantes dans la gestion de contenu',
     'Quelles sont les erreurs courantes à éviter lors de la gestion de contenu avec un CMS ?',
     12, 3, '2024-04-14'),
    ('Intégration des CMS avec les outils marketing',
     'Comment intégrer efficacement votre CMS avec les outils marketing pour une meilleure gestion des campagnes ?',
     12, 4, '2024-04-15'),
    ('Migration d\'un site web vers un nouveau CMS',
     'Quels sont les étapes et les défis à considérer lors de la migration de votre site web vers un nouveau CMS ?',
     12, 5, '2024-04-16'),
    ('Les CMS et le SEO',
     'Comment configurer et optimiser votre CMS pour améliorer le référencement de votre site web ?',
     12, 6, '2024-04-17'),
    ('Les CMS et la gestion des médias',
     'Comment gérer efficacement les médias (images, vidéos) dans votre CMS ?',
     12, 7, '2024-04-18'),
    ('Les tendances futures des systèmes de gestion de contenu',
     'Quelles sont les tendances futures dans le domaine des systèmes de gestion de contenu ?',
     12, 1, '2024-04-19'),

    -- Posts for topic 13: searchEngineOptimization
    ('Les bases du SEO',
     'Quelles sont les bases du SEO que tout développeur web devrait connaître ?',
     13, 1, '2024-04-08'),
    ('Les erreurs courantes en SEO',
     'Quelles sont les erreurs courantes à éviter en SEO pour améliorer le classement de votre site web ?',
     13, 2, '2024-04-09'),
    ('SEO on-page et SEO off-page',
     'Quelle est la différence entre le SEO on-page et le SEO off-page, et comment optimiser les deux ?',
     13, 3, '2024-04-10'),
    ('Les meilleures pratiques pour les balises méta',
     'Quelles sont les meilleures pratiques pour utiliser les balises méta pour le SEO ?',
     13, 4, '2024-04-11'),
    ('Les backlinks et leur importance en SEO',
     'Comment obtenir des backlinks de qualité pour améliorer le SEO de votre site web ?',
     13, 5, '2024-04-12'),
    ('SEO et contenu de qualité',
     'Comment créer du contenu de qualité qui améliore le SEO de votre site web ?',
     13, 6, '2024-04-13'),
    ('Les outils SEO indispensables',
     'Quels sont les outils SEO indispensables pour analyser et améliorer le référencement de votre site web ?',
     13, 7, '2024-04-14'),
    ('SEO et performance du site web',
     'Comment les performances de votre site web affectent-elles le SEO et comment les optimiser ?',
     13, 1, '2024-04-15'),
    ('SEO et mobile-first indexing',
     'Qu\'est-ce que le mobile-first indexing et comment optimiser votre site pour en tirer parti ?',
     13, 2, '2024-04-16'),
    ('SEO local',
     'Comment optimiser votre site web pour le SEO local et attirer des clients locaux ?',
     13, 3, '2024-04-17'),
    ('SEO et réseaux sociaux',
     'Comment les réseaux sociaux peuvent-ils influencer le SEO de votre site web ?',
     13, 4, '2024-04-18'),
    ('Les mises à jour d\'algorithmes de Google',
     'Comment les mises à jour d\'algorithmes de Google affectent-elles le SEO et comment s\'y préparer ?',
     13, 5, '2024-04-19'),
    ('SEO et expérience utilisateur',
     'Comment améliorer l\'expérience utilisateur pour favoriser le SEO de votre site web ?',
     13, 6, '2024-04-20'),
    ('SEO technique',
     'Quels sont les aspects techniques du SEO que vous devez maîtriser pour optimiser votre site web ?',
     13, 7, '2024-04-21'),
    ('SEO et contenu multilingue',
     'Comment optimiser votre site web pour le SEO lorsque vous proposez du contenu multilingue ?',
     13, 1, '2024-04-22'),

    -- Posts for topic 14: webAccessibility
    ('Les principes de base de l\'accessibilité web',
     'Quels sont les principes de base de l\'accessibilité web que tout développeur devrait connaître ?',
     14, 5, '2024-04-08'),
    ('Les outils pour tester l\'accessibilité web',
     'Quels sont les outils les plus efficaces pour tester l\'accessibilité de votre site web ?',
     14, 6, '2024-04-09'),
    ('Les erreurs courantes en matière d\'accessibilité web',
     'Quelles sont les erreurs courantes à éviter pour assurer l\'accessibilité de votre site web ?',
     14, 7, '2024-04-10'),
    ('Les meilleures pratiques pour l\'accessibilité des formulaires',
     'Quelles sont les meilleures pratiques pour rendre vos formulaires web accessibles à tous les utilisateurs ?',
     14, 1, '2024-04-11'),
    ('Accessibilité des contenus multimédia',
     'Comment rendre les contenus multimédia (vidéos, images) accessibles sur votre site web ?',
     14, 2, '2024-04-12'),
    ('Les standards et directives pour l\'accessibilité web',
     'Quels sont les principaux standards et directives à suivre pour garantir l\'accessibilité web ?',
     14, 3, '2024-04-13'),
    ('Accessibilité web et SEO',
     'Comment l\'accessibilité web peut-elle également améliorer le SEO de votre site ?',
     14, 4, '2024-04-14'),
    ('Les avantages commerciaux de l\'accessibilité web',
     'Quels sont les avantages commerciaux d\'un site web accessible pour votre entreprise ?',
     14, 5, '2024-04-15'),
    ('Les aspects techniques de l\'accessibilité web',
     'Quels sont les aspects techniques à prendre en compte pour améliorer l\'accessibilité de votre site web ?',
     14, 6, '2024-04-16'),
    ('L\'accessibilité des sites web mobiles',
     'Comment rendre votre site web mobile accessible à tous les utilisateurs, y compris ceux en situation de handicap ?',
     14, 7, '2024-04-17'),
    ('Les tests utilisateurs pour l\'accessibilité web',
     'Comment effectuer des tests utilisateurs pour vérifier l\'accessibilité de votre site web ?',
     14, 1, '2024-04-18'),
    ('L\'accessibilité et les frameworks JavaScript',
     'Comment garantir l\'accessibilité de votre site web lorsqu\'il est construit avec des frameworks JavaScript modernes ?',
     14, 2, '2024-04-19'),
    ('Les ressources et formations pour l\'accessibilité web',
     'Quelles sont les ressources et formations recommandées pour apprendre l\'accessibilité web ?',
     14, 3, '2024-04-20'),
    ('L\'accessibilité et la conception de l\'interface utilisateur',
     'Comment intégrer les principes d\'accessibilité dès la phase de conception de l\'interface utilisateur ?',
     14, 4, '2024-04-21'),

    -- Posts for topic 15: crossBrowserCompatibility
    ('Les bases de la compatibilité entre navigateurs',
     'Quels sont les éléments essentiels à connaître pour assurer la compatibilité entre différents navigateurs web ?',
     15, 3, '2024-04-08'),
    ('Les outils pour tester la compatibilité entre navigateurs',
     'Quels sont les outils les plus efficaces pour tester la compatibilité de votre site web entre différents navigateurs ?',
     15, 4, '2024-04-09'),
    ('Les problèmes courants de compatibilité entre navigateurs',
     'Quels sont les problèmes de compatibilité entre navigateurs les plus courants et comment les résoudre ?',
     15, 5, '2024-04-10'),
    ('Les meilleures pratiques pour le CSS compatible entre navigateurs',
     'Quelles sont les meilleures pratiques pour écrire du CSS compatible avec tous les navigateurs ?',
     15, 6, '2024-04-11'),
    ('Compatibilité entre navigateurs et JavaScript',
     'Comment écrire du JavaScript qui fonctionne correctement sur tous les navigateurs modernes ?',
     15, 7, '2024-04-12'),
    ('Les polyfills et leur utilisation',
     'Qu\'est-ce qu\'un polyfill et comment l\'utiliser pour assurer la compatibilité entre navigateurs ?',
     15, 1, '2024-04-13'),
    ('Les préfixes CSS pour la compatibilité entre navigateurs',
     'Comment utiliser les préfixes CSS pour garantir la compatibilité de votre site sur tous les navigateurs ?',
     15, 2, '2024-04-14'),
    ('Les frameworks et bibliothèques pour la compatibilité entre navigateurs',
     'Quels frameworks et bibliothèques peuvent vous aider à gérer la compatibilité entre navigateurs ?',
     15, 3, '2024-04-15'),
    ('Les erreurs courantes en compatibilité entre navigateurs',
     'Quelles sont les erreurs courantes à éviter pour garantir une bonne compatibilité entre navigateurs ?',
     15, 4, '2024-04-16'),
    ('Compatibilité entre navigateurs et performance du site web',
     'Comment les questions de compatibilité entre navigateurs peuvent-elles affecter les performances de votre site web ?',
     15, 5, '2024-04-17'),
    ('Les tests automatisés pour la compatibilité entre navigateurs',
     'Comment mettre en place des tests automatisés pour vérifier la compatibilité de votre site entre navigateurs ?',
     15, 6, '2024-04-18'),
    ('Compatibilité entre navigateurs et versions anciennes',
     'Comment gérer la compatibilité avec les versions anciennes des navigateurs web ?',
     15, 7, '2024-04-19'),
    ('Les ressources pour apprendre la compatibilité entre navigateurs',
     'Quelles sont les meilleures ressources pour apprendre et maîtriser la compatibilité entre navigateurs ?',
     15, 1, '2024-04-20'),
    ('Les problèmes de compatibilité entre navigateurs et solutions',
     'Quels sont les problèmes de compatibilité les plus fréquents et comment les résoudre efficacement ?',
     15, 2, '2024-04-21'),

    -- Posts for topic 16: performanceOptimization
    ('Les bases de l\'optimisation des performances web',
     'Quels sont les concepts de base de l\'optimisation des performances web que tout développeur doit connaître ?',
     16, 3, '2024-04-08'),
    ('Les outils pour mesurer les performances web',
     'Quels sont les outils les plus efficaces pour mesurer les performances de votre site web ?',
     16, 4, '2024-04-09'),
    ('Les erreurs courantes en optimisation des performances web',
     'Quelles sont les erreurs courantes à éviter pour optimiser les performances de votre site web ?',
     16, 5, '2024-04-10'),
    ('Les meilleures pratiques pour optimiser les images',
     'Quelles sont les meilleures pratiques pour optimiser les images et améliorer les performances de votre site web ?',
     16, 6, '2024-04-11'),
    ('L\'optimisation du code JavaScript',
     'Comment optimiser votre code JavaScript pour améliorer les performances de votre site web ?',
     16, 7, '2024-04-12'),
    ('Les techniques de mise en cache',
     'Quelles sont les techniques de mise en cache les plus efficaces pour améliorer les performances de votre site web ?',
     16, 1, '2024-04-13'),
    ('La minimisation et la compression des fichiers',
     'Comment minimiser et compresser vos fichiers pour améliorer les temps de chargement de votre site web ?',
     16, 2, '2024-04-14'),
    ('Les CDN et leur rôle dans l\'optimisation des performances',
     'Comment les réseaux de distribution de contenu (CDN) peuvent-ils améliorer les performances de votre site web ?',
     16, 3, '2024-04-15'),
    ('Les tests de performance automatisés',
     'Comment mettre en place des tests de performance automatisés pour surveiller et améliorer votre site web ?',
     16, 4, '2024-04-16'),
    ('Les performances web et l\'expérience utilisateur',
     'Comment les performances de votre site web influencent-elles l\'expérience utilisateur et les taux de conversion ?',
     16, 5, '2024-04-17'),
    ('L\'optimisation des performances côté serveur',
     'Quelles sont les meilleures pratiques pour optimiser les performances de votre site web côté serveur ?',
     16, 6, '2024-04-18'),
    ('Les ressources pour apprendre l\'optimisation des performances web',
     'Quelles sont les meilleures ressources pour apprendre et maîtriser l\'optimisation des performances web ?',
     16, 7, '2024-04-19'),
    ('Les performances web et le mobile',
     'Comment optimiser les performances de votre site web pour les utilisateurs mobiles ?',
     16, 1, '2024-04-20'),
    ('L\'importance de la performance web pour le SEO',
     'Pourquoi la performance de votre site web est-elle cruciale pour le SEO et comment l\'optimiser ?',
     16, 2, '2024-04-21'),
    ('Les frameworks et bibliothèques pour l\'optimisation des performances',
     'Quels frameworks et bibliothèques peuvent vous aider à améliorer les performances de votre site web ?',
     16, 3, '2024-04-22'),
    -- Posts for topic 17: microservices
    ('Introduction aux microservices',
     'Qu\'est-ce que l\'architecture microservices et comment diffère-t-elle de l\'architecture monolithique ?',
     17, 6, '2024-04-08'),
    ('Les avantages des microservices',
     'Quels sont les principaux avantages d\'utiliser une architecture microservices pour votre application ?',
     17, 1, '2024-04-09'),
    ('Les défis des microservices',
     'Quels sont les défis courants associés à l\'architecture microservices et comment les surmonter ?',
     17, 2, '2024-04-10'),
    ('Microservices et communication entre services',
     'Comment gérer la communication entre les différents microservices dans une architecture distribuée ?',
     17, 3, '2024-04-11'),
    ('Les outils pour les microservices',
     'Quels outils et frameworks peuvent vous aider à développer et gérer des microservices ?',
     17, 4, '2024-04-12'),
    ('Microservices et sécurité',
     'Quelles sont les meilleures pratiques pour sécuriser les microservices dans une architecture distribuée ?',
     17, 5, '2024-04-13'),
    ('Les patterns de conception pour les microservices',
     'Quels sont les patterns de conception courants utilisés dans les architectures microservices ?',
     17, 6, '2024-04-14'),
    ('Gestion des données dans une architecture microservices',
     'Comment gérer les données efficacement dans une architecture basée sur des microservices ?',
     17, 7, '2024-04-15'),
    ('Microservices et déploiement continu',
     'Comment les microservices facilitent-ils le déploiement continu et l\'intégration continue ?',
     17, 1, '2024-04-16'),
    ('Les erreurs courantes avec les microservices',
     'Quelles sont les erreurs courantes à éviter lors de la mise en œuvre d\'une architecture microservices ?',
     17, 2, '2024-04-17'),
    ('Microservices et gestion des configurations',
     'Comment gérer les configurations dans une architecture microservices ?',
     17, 3, '2024-04-18'),
    ('Les performances des microservices',
     'Comment optimiser les performances de votre système basé sur des microservices ?',
     17, 4, '2024-04-19'),
    ('Les microservices et l\'observabilité',
     'Comment assurer l\'observabilité et le suivi dans une architecture microservices ?',
     17, 5, '2024-04-20'),
    ('Les microservices et la résilience',
     'Comment rendre votre architecture microservices plus résiliente face aux pannes et aux erreurs ?',
     17, 6, '2024-04-21'),
    ('Les tendances futures des microservices',
     'Quelles sont les tendances émergentes dans le domaine des microservices et comment s\'y préparer ?',
     17, 7, '2024-04-22'),

    -- Posts for topic 18: unitTesting
    ('Introduction aux tests unitaires',
     'Qu\'est-ce que les tests unitaires et pourquoi sont-ils importants dans le développement logiciel ?',
     18, 1, '2024-04-08'),
    ('Les meilleures pratiques pour écrire des tests unitaires',
     'Quelles sont les meilleures pratiques pour écrire des tests unitaires efficaces et maintenables ?',
     18, 2, '2024-04-09'),
    ('Les outils pour les tests unitaires',
     'Quels outils et frameworks recommandez-vous pour les tests unitaires ?',
     18, 3, '2024-04-10'),
    ('Les erreurs courantes en tests unitaires',
     'Quelles sont les erreurs courantes à éviter lors de l\'écriture et de l\'exécution des tests unitaires ?',
     18, 4, '2024-04-11'),
    ('Les tests unitaires et les tests d\'intégration',
     'Quelle est la différence entre les tests unitaires et les tests d\'intégration, et comment les utiliser efficacement ?',
     18, 5, '2024-04-12'),
    ('Les mocks et les stubs en tests unitaires',
     'Comment utiliser les mocks et les stubs pour isoler les unités de code dans vos tests unitaires ?',
     18, 6, '2024-04-13'),
    ('Les tests unitaires dans le développement agile',
     'Comment intégrer les tests unitaires dans un processus de développement agile ?',
     18, 7, '2024-04-14'),
    ('Les tests unitaires et le code legacy',
     'Comment appliquer des tests unitaires sur du code legacy et améliorer sa maintenabilité ?',
     18, 1, '2024-04-15'),
    ('Les performances des tests unitaires',
     'Comment optimiser les performances de vos tests unitaires pour accélérer le cycle de développement ?',
     18, 2, '2024-04-16'),
    ('Les tests unitaires et la couverture de code',
     'Comment mesurer et améliorer la couverture de code avec vos tests unitaires ?',
     18, 3, '2024-04-17'),
    ('Les tests unitaires et les bonnes pratiques de codage',
     'Comment les bonnes pratiques de codage influencent-elles la qualité de vos tests unitaires ?',
     18, 4, '2024-04-18'),
    ('Les outils de CI/CD pour les tests unitaires',
     'Comment intégrer les tests unitaires dans votre pipeline CI/CD pour une validation continue ?',
     18, 5, '2024-04-19'),
    ('Les tests unitaires et les performances de l\'application',
     'Comment les tests unitaires contribuent-ils à la performance globale de votre application ?',
     18, 6, '2024-04-20'),
    ('Les tendances en matière de tests unitaires',
     'Quelles sont les tendances actuelles et les innovations dans le domaine des tests unitaires ?',
     18, 7, '2024-04-21'),
    ('Les ressources pour apprendre les tests unitaires',
     'Quelles ressources recommandez-vous pour approfondir vos connaissances en tests unitaires ?',
     18, 1, '2024-04-22'),

    -- Posts for topic 19: endToEndTesting
    ('Introduction aux tests end-to-end',
     'Qu\'est-ce que les tests end-to-end et pourquoi sont-ils cruciaux pour assurer la qualité des applications ?',
     19, 7, '2024-04-08'),
    ('Les outils pour les tests end-to-end',
     'Quels outils et frameworks recommandez-vous pour les tests end-to-end ?',
     19, 1, '2024-04-09'),
    ('Les meilleures pratiques pour les tests end-to-end',
     'Quelles sont les meilleures pratiques pour écrire et exécuter des tests end-to-end efficaces ?',
     19, 2, '2024-04-10'),
    ('Les erreurs courantes en tests end-to-end',
     'Quelles sont les erreurs courantes à éviter lors de la mise en œuvre des tests end-to-end ?',
     19, 3, '2024-04-11'),
    ('Les tests end-to-end et le développement agile',
     'Comment intégrer les tests end-to-end dans un environnement de développement agile ?',
     19, 4, '2024-04-12'),
    ('Les tests end-to-end et les tests unitaires',
     'Quelle est la relation entre les tests end-to-end et les tests unitaires, et comment les combiner efficacement ?',
     19, 5, '2024-04-13'),
    ('Les défis des tests end-to-end',
     'Quels sont les principaux défis liés aux tests end-to-end et comment les surmonter ?',
     19, 6, '2024-04-14'),
    ('Les performances des tests end-to-end',
     'Comment optimiser les performances et le temps d\'exécution des tests end-to-end ?',
     19, 7, '2024-04-15'),
    ('Les tests end-to-end dans le pipeline CI/CD',
     'Comment intégrer les tests end-to-end dans votre pipeline CI/CD pour une validation continue ?',
     19, 1, '2024-04-16'),
    ('Les tests end-to-end et les environnements de test',
     'Comment préparer et gérer les environnements de test pour des tests end-to-end efficaces ?',
     19, 2, '2024-04-17'),
    ('Les tests end-to-end et les utilisateurs réels',
     'Comment simuler les interactions des utilisateurs réels dans vos tests end-to-end ?',
     19, 3, '2024-04-18'),
    ('Les outils de reporting pour les tests end-to-end',
     'Quels outils de reporting utilisez-vous pour analyser les résultats des tests end-to-end ?',
     19, 4, '2024-04-19'),
    ('Les tendances dans les tests end-to-end',
     'Quelles sont les tendances actuelles et les nouvelles pratiques dans le domaine des tests end-to-end ?',
     19, 5, '2024-04-20'),
    ('Les tests end-to-end pour les applications mobiles',
     'Comment adapter les tests end-to-end pour les applications mobiles et les environnements multi-plateformes ?',
     19, 6, '2024-04-21'),
    ('Les ressources pour apprendre les tests end-to-end',
     'Quelles ressources recommandez-vous pour maîtriser les tests end-to-end ?',
     19, 7, '2024-04-22'),

    -- Posts for topic 20: databaseDesign
    ('Introduction à la conception de bases de données',
     'Quelles sont les bases de la conception de bases de données et pourquoi est-elle importante pour les applications ?',
     20, 2, '2024-04-08'),
    ('Les principes de la normalisation des bases de données',
     'Quels sont les principes de la normalisation des bases de données et comment les appliquer ?',
     20, 3, '2024-04-09'),
    ('Les modèles de données relationnels et non relationnels',
     'Quelle est la différence entre les modèles de données relationnels et non relationnels ?',
     20, 4, '2024-04-10'),
    ('Les meilleures pratiques pour la conception de schémas',
     'Quelles sont les meilleures pratiques pour concevoir des schémas de bases de données efficaces ?',
     20, 5, '2024-04-11'),
    ('Les outils pour la conception de bases de données',
     'Quels outils et logiciels pouvez-vous utiliser pour concevoir des bases de données ?',
     20, 6, '2024-04-12'),
    ('Les défis courants en conception de bases de données',
     'Quels sont les défis courants en conception de bases de données et comment les surmonter ?',
     20, 7, '2024-04-13'),
    ('Les bases de données et la performance',
     'Comment la conception de bases de données affecte-t-elle les performances des applications ?',
     20, 1, '2024-04-14'),
    ('Les tendances en conception de bases de données',
     'Quelles sont les tendances actuelles dans la conception de bases de données et comment s\'adapter à ces évolutions ?',
     20, 2, '2024-04-15'),
    ('Les bases de données et la sécurité',
     'Comment assurer la sécurité des données dans une base de données ?',
     20, 3, '2024-04-16'),
    ('Les bases de données distribuées',
     'Quels sont les avantages et les défis des bases de données distribuées ?',
     20, 4, '2024-04-17'),
    ('Les bases de données et les transactions',
     'Comment gérer les transactions dans une base de données pour assurer la cohérence des données ?',
     20, 5, '2024-04-18'),
    ('Les bases de données et le cloud',
     'Comment la conception des bases de données change-t-elle avec les solutions cloud ?',
     20, 6, '2024-04-19'),
    ('Les erreurs courantes en conception de bases de données',
     'Quelles sont les erreurs courantes à éviter lors de la conception de bases de données ?',
     20, 7, '2024-04-20'),
    ('Les ressources pour apprendre la conception de bases de données',
     'Quelles sont les meilleures ressources pour maîtriser la conception de bases de données ?',
     20, 1, '2024-04-21'),
    ('Les bases de données et l\'analyse de données',
     'Comment la conception de bases de données influence-t-elle l\'analyse et l\'exploitation des données ?',
     20, 2, '2024-04-22'),

    -- Posts for topic 21: versionControl
    ('Introduction au contrôle de version',
     'Qu\'est-ce que le contrôle de version et pourquoi est-il essentiel pour le développement logiciel ?',
     21, 6, '2024-04-08'),
    ('Les outils de contrôle de version les plus populaires',
     'Quels sont les outils de contrôle de version les plus utilisés et comment choisir celui qui convient à votre projet ?',
     21, 1, '2024-04-09'),
    ('Les bonnes pratiques de contrôle de version',
     'Quelles sont les meilleures pratiques pour utiliser efficacement un système de contrôle de version ?',
     21, 2, '2024-04-10'),
    ('Les branches et les workflows en contrôle de version',
     'Comment gérer les branches et choisir le bon workflow pour votre projet de développement ?',
     21, 3, '2024-04-11'),
    ('Les erreurs courantes en contrôle de version',
     'Quelles sont les erreurs courantes à éviter lors de l\'utilisation d\'un système de contrôle de version ?',
     21, 4, '2024-04-12'),
    ('Les merges et les conflits en contrôle de version',
     'Comment gérer les merges et résoudre les conflits dans un système de contrôle de version ?',
     21, 5, '2024-04-13'),
    ('Le contrôle de version dans le développement agile',
     'Comment intégrer le contrôle de version dans un processus de développement agile ?',
     21, 6, '2024-04-14'),
    ('Les outils de collaboration avec le contrôle de version',
     'Quels outils facilitent la collaboration et la gestion des versions dans les projets d\'équipe ?',
     21, 7, '2024-04-15'),
    ('Les branches et le versionnage sémantique',
     'Comment utiliser le versionnage sémantique avec les branches pour une gestion de versions efficace ?',
     21, 1, '2024-04-16'),
    ('Les meilleures pratiques pour les commits',
     'Quelles sont les meilleures pratiques pour rédiger des messages de commit clairs et utiles ?',
     21, 2, '2024-04-17'),
    ('Le contrôle de version pour les projets open source',
     'Comment gérer le contrôle de version pour les projets open source et encourager la contribution ?',
     21, 3, '2024-04-18'),
    ('Les tendances en matière de contrôle de version',
     'Quelles sont les tendances actuelles et les évolutions dans le domaine du contrôle de version ?',
     21, 4, '2024-04-19'),
    ('Les ressources pour maîtriser le contrôle de version',
     'Quelles sont les meilleures ressources pour apprendre et maîtriser le contrôle de version ?',
     21, 5, '2024-04-20'),
    ('Les intégrations continues et le contrôle de version',
     'Comment utiliser le contrôle de version avec les outils d\'intégration continue pour automatiser le développement ?',
     21, 6, '2024-04-21'),
    ('Les outils de visualisation pour le contrôle de version',
     'Quels outils de visualisation pouvez-vous utiliser pour mieux comprendre l\'historique des versions de votre projet ?',
     21, 7, '2024-04-22');
