INSERT INTO posts (Title, Content, Id_topics, Id_User, Create_post)
VALUES
    -- Posts for topic 1: carrouselsJs
    ('Faut mieux faire un carrousel en natif ou avec bibliothèque ?',
     'Je suis en train de faire une boutique en js et je veux faire un carrousel pour afficher mes articles et j\'essaye de bien opti mon code donc je ne sais pas si je dois me faciliter la vie en utilisant swiper par exemple mais donc importer toutes une bibliothèque où me complexifier la vie en créant ma fonction qui fait le carrousel',
     1, 1, '2024-04-03'),
    ('Quelle bibliothèque de carrousel JavaScript recommandez-vous ?',
     'Je cherche une bibliothèque JavaScript légère pour créer un carrousel performant sur mon site web. Des recommandations ?',
     1, 2, '2024-04-04'),
    ('Comment optimiser les carrousels pour le SEO ?',
     'Quels sont les aspects à considérer pour s\'assurer que les carrousels JavaScript ne nuisent pas au référencement SEO de mon site ?',
     1, 3, '2024-04-05'),
    ('Les meilleures pratiques pour les carrousels en JavaScript',
     'Quelles sont les meilleures pratiques pour créer des carrousels fluides et performants en JavaScript ?',
     1, 4, '2024-04-06'),
    ('Gérer la compatibilité des carrousels JavaScript sur mobile',
     'Comment assurer que mon carrousel JavaScript fonctionne bien sur les appareils mobiles ?',
     1, 5, '2024-04-07'),
    ('Les erreurs courantes lors de la création de carrousels en JavaScript',
     'Quelles sont les erreurs courantes à éviter lors de la création de carrousels en JavaScript ?',
     1, 6, '2024-04-08'),
    ('Carrousels JavaScript et accessibilité',
     'Comment rendre les carrousels JavaScript accessibles pour les utilisateurs ayant des handicaps ?',
     1, 7, '2024-04-09'),
    ('Utilisation de carrousels pour afficher des produits',
     'Quels sont les avantages d\'utiliser un carrousel pour afficher des produits sur une boutique en ligne ?',
     1, 1, '2024-04-10'),
    ('Personnalisation de carrousels avec JavaScript',
     'Comment personnaliser les carrousels JavaScript pour qu\'ils s\'adaptent à mon thème de site web ?',
     1, 2, '2024-04-11'),
    ('Carrousels JavaScript et performances',
     'Comment optimiser les performances des carrousels JavaScript pour qu\'ils se chargent rapidement ?',
     1, 3, '2024-04-12'),
    ('Les meilleurs plugins de carrousel pour JavaScript en 2024',
     'Quels sont les plugins de carrousel JavaScript les plus recommandés en 2024 ?',
     1, 4, '2024-04-13'),
    ('Intégration de carrousels JavaScript dans un site WordPress',
     'Quelles sont les étapes pour intégrer un carrousel JavaScript dans un site WordPress ?',
     1, 5, '2024-04-14'),
    ('Alternatives aux carrousels JavaScript',
     'Quelles sont les alternatives aux carrousels JavaScript pour afficher du contenu de manière interactive ?',
     1, 6, '2024-04-15'),
    ('Troubleshooting des carrousels JavaScript',
     'Comment dépanner et résoudre les problèmes courants avec les carrousels JavaScript ?',
     1, 7, '2024-04-16'),
    ('Carrousels JavaScript pour les débutants',
     'Quels sont les conseils pour les débutants qui souhaitent créer leur premier carrousel en JavaScript ?',
     1, 1, '2024-04-17'),

    -- Posts for topic 2: responsive
    ('Comment gérer les points de rupture pour un site responsive ?',
     'Quels sont les points de rupture standards à utiliser pour un site web réactif et comment les gérer efficacement ?',
     2, 2, '2024-04-04'),
    ('Meilleures pratiques pour le design responsive',
     'Quelles sont les meilleures pratiques pour créer un design responsive qui fonctionne sur tous les appareils ?',
     2, 3, '2024-04-05'),
    ('Frameworks CSS pour un design responsive',
     'Quels sont les meilleurs frameworks CSS à utiliser pour un design responsive ?',
     2, 4, '2024-04-06'),
    ('Test de la réactivité d\'un site web',
     'Quels outils recommandez-vous pour tester la réactivité d\'un site web sur différents appareils ?',
     2, 5, '2024-04-07'),
    ('Fluidité du design responsive',
     'Comment s\'assurer que le design responsive de mon site est fluide et sans ruptures ?',
     2, 6, '2024-04-08'),
    ('Optimisation des images pour un site responsive',
     'Quelles techniques utiliser pour optimiser les images sur un site responsive ?',
     2, 7, '2024-04-09'),
    ('Grilles CSS pour un design responsive',
     'Comment utiliser les grilles CSS pour créer un design responsive efficace ?',
     2, 1, '2024-04-10'),
    ('Responsive design et SEO',
     'Comment le responsive design impacte-t-il le SEO de votre site web ?',
     2, 2, '2024-04-11'),
    ('Approches pour le design mobile-first',
     'Quels sont les avantages de l\'approche mobile-first pour le design responsive ?',
     2, 3, '2024-04-12'),
    ('Gestion des polices dans un design responsive',
     'Comment gérer les tailles de polices dans un design responsive pour garantir la lisibilité sur tous les appareils ?',
     2, 4, '2024-04-13'),
    ('Utilisation de media queries pour un design responsive',
     'Comment utiliser efficacement les media queries pour créer un design responsive ?',
     2, 5, '2024-04-14'),
    ('CSS Grid vs Flexbox pour un design responsive',
     'Quel est le meilleur choix entre CSS Grid et Flexbox pour un design responsive et pourquoi ?',
     2, 6, '2024-04-15'),
    ('Défis du design responsive et comment les surmonter',
     'Quels sont les principaux défis du design responsive et comment les surmonter ?',
     2, 7, '2024-04-16'),
    ('Compatibilité des navigateurs et design responsive',
     'Comment s\'assurer que le design responsive de votre site est compatible avec tous les navigateurs ?',
     2, 1, '2024-04-17'),
    ('Utilisation de frameworks JavaScript pour un design responsive',
     'Quels frameworks JavaScript sont recommandés pour améliorer un design responsive ?',
     2, 2, '2024-04-18'),

    -- Posts for topic 3: animationsCss
    ('Les meilleures pratiques pour les animations CSS ?',
     'Quelles sont les meilleures pratiques pour créer des animations fluides et performantes en CSS ?',
     3, 4, '2024-04-05'),
    ('Introduction aux animations CSS',
     'Comment démarrer avec les animations CSS pour ajouter des effets visuels à votre site web ?',
     3, 5, '2024-04-06'),
    ('Animations CSS et performances web',
     'Comment optimiser les animations CSS pour qu\'elles n\'impactent pas négativement les performances de votre site web ?',
     3, 6, '2024-04-07'),
    ('Utilisation des keyframes en CSS',
     'Comment utiliser les keyframes en CSS pour créer des animations complexes ?',
     3, 7, '2024-04-08'),
    ('CSS transitions vs animations',
     'Quand utiliser les transitions CSS par rapport aux animations CSS pour obtenir les meilleurs résultats ?',
     3, 1, '2024-04-09'),
    ('Animations CSS et accessibilité',
     'Comment s\'assurer que les animations CSS n\'entravent pas l\'accessibilité de votre site web ?',
     3, 2, '2024-04-10'),
    ('Les effets de hover en CSS',
     'Quels sont les effets de hover en CSS les plus populaires et comment les implémenter ?',
     3, 3, '2024-04-11'),
    ('Animations CSS pour les boutons',
     'Quelles sont les meilleures pratiques pour ajouter des animations CSS aux boutons de votre site web ?',
     3, 4, '2024-04-12'),
    ('Animations CSS et JavaScript',
     'Comment combiner CSS et JavaScript pour créer des animations plus interactives et dynamiques ?',
     3, 5, '2024-04-13'),
    ('Utilisation des préprocesseurs CSS pour les animations',
     'Comment les préprocesseurs CSS comme Sass ou LESS peuvent-ils simplifier la création d\'animations CSS ?',
     3, 6, '2024-04-14'),
    ('Animations CSS et compatibilité des navigateurs',
     'Comment s\'assurer que vos animations CSS sont compatibles avec tous les navigateurs ?',
     3, 7, '2024-04-15'),
    ('Les outils pour créer des animations CSS',
     'Quels outils recommandez-vous pour faciliter la création d\'animations CSS ?',
     3, 1, '2024-04-16'),
    ('Animations CSS pour le défilement',
     'Comment ajouter des animations CSS lors du défilement de la page pour améliorer l\'expérience utilisateur ?',
     3, 2, '2024-04-17'),
    ('Optimiser les animations CSS pour les appareils mobiles',
     'Quelles sont les meilleures pratiques pour optimiser les animations CSS pour les appareils mobiles ?',
     3, 3, '2024-04-18'),
    ('Exemples d\'animations CSS inspirantes',
     'Quels sont les exemples d\'animations CSS inspirantes que vous avez vus récemment et comment les recréer ?',
     3, 4, '2024-04-19'),

    -- Posts for topic 4: darkMode
    ('Avantages du mode sombre pour les utilisateurs',
     'Quels sont les avantages du mode sombre pour les utilisateurs et comment l\'implémenter efficacement sur un site web ?',
     4, 5, '2024-04-06'),
    ('Implémenter le mode sombre avec CSS variables',
     'Comment utiliser les variables CSS pour implémenter un mode sombre sur votre site web ?',
     4, 6, '2024-04-07'),
    ('Switch entre mode clair et mode sombre',
     'Quels sont les moyens les plus simples et efficaces pour permettre aux utilisateurs de passer du mode clair au mode sombre ?',
     4, 7, '2024-04-08'),
    ('Le mode sombre et la consommation d\'énergie',
     'Comment le mode sombre peut-il aider à réduire la consommation d\'énergie des appareils ?',
     4, 1, '2024-04-09'),
    ('Les meilleures pratiques pour le design en mode sombre',
     'Quelles sont les meilleures pratiques pour concevoir des interfaces utilisateur en mode sombre ?',
     4, 2, '2024-04-10'),
    ('Accessibilité du mode sombre',
     'Comment s\'assurer que le mode sombre reste accessible pour tous les utilisateurs, y compris ceux avec des déficiences visuelles ?',
     4, 3, '2024-04-11'),
    ('Mode sombre et branding',
     'Comment maintenir la cohérence de la marque lorsque vous implémentez un mode sombre sur votre site ?',
     4, 4, '2024-04-12'),
    ('Mode sombre automatique basé sur les préférences système',
     'Comment configurer votre site web pour qu\'il bascule automatiquement en mode sombre en fonction des préférences système de l\'utilisateur ?',
     4, 5, '2024-04-13'),
    ('Les défis du mode sombre',
     'Quels sont les défis courants lors de l\'implémentation du mode sombre et comment les surmonter ?',
     4, 6, '2024-04-14'),
    ('Mode sombre et expérience utilisateur',
     'Comment le mode sombre peut-il améliorer l\'expérience utilisateur et quelles sont les meilleures pratiques pour le mettre en place ?',
     4, 7, '2024-04-15'),
    ('Exemples de sites web avec un excellent mode sombre',
     'Quels sont les exemples de sites web avec un mode sombre bien implémenté et pourquoi sont-ils réussis ?',
     4, 1, '2024-04-16'),
    ('Impact du mode sombre sur la lisibilité',
     'Comment le mode sombre affecte-t-il la lisibilité du texte et quelles sont les solutions pour améliorer cela ?',
     4, 2, '2024-04-17'),
    ('Mode sombre et CSS media queries',
     'Comment utiliser les media queries CSS pour implémenter un mode sombre sur votre site web ?',
     4, 3, '2024-04-18'),
    ('Mode sombre et animations CSS',
     'Comment créer des animations CSS qui fonctionnent bien en mode sombre sans être distrayantes ?',
     4, 4, '2024-04-19'),
    ('Mode sombre pour les applications mobiles',
     'Quelles sont les considérations spécifiques pour implémenter un mode sombre dans les applications mobiles ?',
     4, 5, '2024-04-20'),

    -- Posts for topic 5: formValidation
    ('Validation des formulaires en JavaScript vs HTML5',
     'Quelle est la meilleure approche pour valider les formulaires, en utilisant JavaScript ou les attributs HTML5 ?',
     5, 6, '2024-04-07'),
    ('Les meilleures bibliothèques pour la validation de formulaires',
     'Quelles sont les bibliothèques JavaScript les plus efficaces pour la validation des formulaires ?',
     5, 7, '2024-04-08'),
    ('Validation de formulaire côté client vs côté serveur',
     'Quels sont les avantages et les inconvénients de la validation de formulaire côté client par rapport à la validation côté serveur ?',
     5, 1, '2024-04-09'),
    ('Validation des formulaires et accessibilité',
     'Comment rendre la validation des formulaires accessible aux utilisateurs ayant des déficiences ?',
     5, 2, '2024-04-10'),
    ('Gestion des erreurs de validation en temps réel',
     'Comment gérer et afficher les erreurs de validation des formulaires en temps réel pour une meilleure expérience utilisateur ?',
     5, 3, '2024-04-11'),
    ('Meilleures pratiques pour la validation des formulaires HTML5',
     'Quelles sont les meilleures pratiques pour tirer parti des fonctionnalités de validation intégrées dans HTML5 ?',
     5, 4, '2024-04-12'),
    ('Utilisation de regex pour la validation des formulaires',
     'Comment utiliser les expressions régulières (regex) pour valider les champs de formulaire de manière efficace ?',
     5, 5, '2024-04-13'),
    ('Validation des formulaires pour les données sensibles',
     'Quelles sont les considérations de sécurité à prendre en compte lors de la validation de formulaires contenant des données sensibles ?',
     5, 6, '2024-04-14'),
    ('Gestion des formulaires multi-étapes',
     'Comment gérer la validation des formulaires multi-étapes pour assurer une saisie correcte des données ?',
     5, 7, '2024-04-15'),
    ('Tests unitaires pour la validation des formulaires',
     'Comment écrire des tests unitaires pour s\'assurer que la validation des formulaires fonctionne correctement ?',
     5, 1, '2024-04-16'),
    ('Les erreurs de validation les plus courantes et comment les éviter',
     'Quelles sont les erreurs de validation de formulaire les plus courantes et comment les éviter ?',
     5, 2, '2024-04-17'),
    ('Validation conditionnelle des champs de formulaire',
     'Comment implémenter une validation conditionnelle pour certains champs de formulaire en fonction des saisies utilisateur ?',
     5, 3, '2024-04-18'),
    ('Expériences utilisateur optimales avec la validation de formulaires',
     'Quelles sont les meilleures pratiques pour offrir une expérience utilisateur optimale avec la validation de formulaires ?',
     5, 4, '2024-04-19'),
    ('Utilisation de bibliothèques de validation pour React',
     'Quelles sont les meilleures bibliothèques de validation de formulaires pour les applications React ?',
     5, 5, '2024-04-20'),

    -- Posts for topic 6: apiIntegration
    ('Intégration d\'API RESTful dans une application web',
     'Quelles sont les étapes pour intégrer une API RESTful dans une application web existante ?',
     6, 2, '2024-04-08'),
    ('Meilleures pratiques pour la sécurité des API',
     'Quelles sont les meilleures pratiques pour sécuriser une API et protéger les données sensibles ?',
     6, 3, '2024-04-09'),
    ('Gestion des erreurs lors de l\'appel d\'une API',
     'Comment gérer les erreurs et exceptions lors de l\'appel d\'une API dans votre application web ?',
     6, 4, '2024-04-10'),
    ('Documentation des API : pourquoi et comment',
     'Pourquoi est-il important de bien documenter votre API et comment le faire de manière efficace ?',
     6, 5, '2024-04-11'),
    ('Utilisation de GraphQL pour les API',
     'Quels sont les avantages de GraphQL par rapport aux API RESTful et comment l\'implémenter ?',
     6, 6, '2024-04-12'),
    ('Authentification et autorisation avec les API',
     'Quelles sont les meilleures pratiques pour gérer l\'authentification et l\'autorisation dans les API ?',
     6, 7, '2024-04-13'),
    ('Les outils pour tester les API',
     'Quels outils recommandez-vous pour tester les API et s\'assurer qu\'elles fonctionnent correctement ?',
     6, 1, '2024-04-14'),
    ('Les performances des API',
     'Comment optimiser les performances de votre API pour qu\'elle réponde rapidement aux requêtes ?',
     6, 2, '2024-04-15'),
    ('Les erreurs courantes lors de l\'intégration des API',
     'Quelles sont les erreurs courantes à éviter lors de l\'intégration d\'une API dans une application web ?',
     6, 3, '2024-04-16'),
    ('Versioning des API : pourquoi et comment le faire',
     'Pourquoi est-il important de versionner une API et comment le faire correctement ?',
     6, 4, '2024-04-17'),
    ('Intégration d\'API dans une application mobile',
     'Quelles sont les particularités de l\'intégration d\'API dans une application mobile par rapport à une application web ?',
     6, 5, '2024-04-18'),
    ('Les meilleures pratiques pour les requêtes API',
     'Quelles sont les meilleures pratiques pour envoyer des requêtes API et gérer les réponses de manière efficace ?',
     6, 6, '2024-04-19'),
    ('API Gateway : rôle et avantages',
     'Quel est le rôle d\'une API Gateway et quels sont ses avantages pour la gestion des API ?',
     6, 7, '2024-04-20'),
    ('Les outils de monitoring pour les API',
     'Quels outils recommandez-vous pour surveiller et analyser les performances des API ?',
     6, 1, '2024-04-21'),
    ('Les meilleures pratiques pour les microservices et les API',
     'Comment les microservices et les API peuvent-ils fonctionner ensemble pour créer une architecture efficace et scalable ?',
     6, 2, '2024-04-22'),

    -- Posts for topic 7: singlePageApplications
    ('Choisir le bon framework pour une Single Page Application',
     'Quels sont les critères pour choisir le bon framework (React, Vue, Angular) pour développer une Single Page Application ?',
     7, 4, '2024-04-09'),
    ('Performance des Single Page Applications',
     'Comment optimiser la performance de votre Single Page Application pour qu\'elle soit rapide et réactive ?',
     7, 5, '2024-04-10'),
    ('Gestion de l\'état dans les Single Page Applications',
     'Quelles sont les meilleures pratiques pour gérer l\'état de votre application dans une Single Page Application ?',
     7, 6, '2024-04-11'),
    ('SEO pour les Single Page Applications',
     'Comment améliorer le SEO de votre Single Page Application pour qu\'elle soit bien référencée par les moteurs de recherche ?',
     7, 7, '2024-04-12'),
    ('Routing dans les Single Page Applications',
     'Comment implémenter un système de routing efficace dans votre Single Page Application ?',
     7, 1, '2024-04-13'),
    ('Les erreurs courantes dans les Single Page Applications',
     'Quelles sont les erreurs courantes à éviter lors du développement de Single Page Applications ?',
     7, 2, '2024-04-14'),
    ('Les bibliothèques d\'animation pour les Single Page Applications',
     'Quelles sont les bibliothèques d\'animation recommandées pour les Single Page Applications et comment les intégrer ?',
     7, 3, '2024-04-15'),
    ('Test des Single Page Applications',
     'Quels sont les outils et les meilleures pratiques pour tester les Single Page Applications ?',
     7, 4, '2024-04-16'),
    ('Les avantages des Single Page Applications',
     'Quels sont les avantages des Single Page Applications par rapport aux applications multi-pages traditionnelles ?',
     7, 5, '2024-04-17'),
    ('Déploiement des Single Page Applications',
     'Quelles sont les meilleures pratiques pour déployer une Single Page Application sur un serveur de production ?',
     7, 6, '2024-04-18'),
    ('Intégration des API dans les Single Page Applications',
     'Comment intégrer efficacement les API dans une Single Page Application pour une interaction fluide avec le backend ?',
     7, 7, '2024-04-19'),
    ('Les défis des Single Page Applications',
     'Quels sont les défis courants lors du développement de Single Page Applications et comment les surmonter ?',
     7, 1, '2024-04-20'),
    ('Les meilleures pratiques pour les Single Page Applications',
     'Quelles sont les meilleures pratiques pour garantir la maintenabilité et la scalabilité des Single Page Applications ?',
     7, 2, '2024-04-21'),
    ('Les outils de développement pour les Single Page Applications',
     'Quels outils de développement recommandez-vous pour accélérer la création de Single Page Applications ?',
     7, 3, '2024-04-22'),
    ('Exemples de Single Page Applications réussies',
     'Quels sont les exemples de Single Page Applications bien conçues et pourquoi sont-elles réussies ?',
     7, 4, '2024-04-23'),

    -- Posts for topic 8: progressiveWebApps
    ('Les avantages des Progressive Web Apps',
     'Quels sont les avantages des Progressive Web Apps par rapport aux applications natives ?',
     8, 5, '2024-04-07'),
    ('Mise en cache et hors ligne dans les Progressive Web Apps',
     'Comment implémenter la mise en cache et la fonctionnalité hors ligne dans une Progressive Web App ?',
     8, 6, '2024-04-08'),
    ('Les meilleures pratiques pour développer une Progressive Web App',
     'Quelles sont les meilleures pratiques pour développer une Progressive Web App performante et fiable ?',
     8, 7, '2024-04-09'),
    ('Les outils pour tester et déboguer les Progressive Web Apps',
     'Quels outils recommandez-vous pour tester et déboguer les Progressive Web Apps ?',
     8, 1, '2024-04-10'),
    ('Les critères pour une bonne Progressive Web App',
     'Quels sont les critères à remplir pour qu\'une Progressive Web App soit considérée comme de haute qualité ?',
     8, 2, '2024-04-11'),
    ('Sécurité dans les Progressive Web Apps',
     'Comment assurer la sécurité de votre Progressive Web App contre les menaces courantes ?',
     8, 3, '2024-04-12'),
    ('Exemples de Progressive Web Apps réussies',
     'Quels sont les exemples de Progressive Web Apps bien conçues et pourquoi sont-elles réussies ?',
     8, 4, '2024-04-13'),
    ('Améliorer les performances des Progressive Web Apps',
     'Quelles sont les techniques pour améliorer les performances des Progressive Web Apps ?',
     8, 5, '2024-04-14'),
    ('Les manifestes et les Progressive Web Apps',
     'Comment configurer et utiliser les manifestes pour les Progressive Web Apps ?',
     8, 6, '2024-04-15'),
    ('Les Progressive Web Apps et le SEO',
     'Comment optimiser les Progressive Web Apps pour le SEO ?',
     8, 7, '2024-04-16'),
    ('Les API des Progressive Web Apps',
     'Quelles sont les principales API à utiliser pour tirer parti des fonctionnalités des Progressive Web Apps ?',
     8, 1, '2024-04-17'),
    ('Service Workers et Progressive Web Apps',
     'Quel est le rôle des Service Workers dans les Progressive Web Apps et comment les implémenter ?',
     8, 2, '2024-04-18'),
    ('Déploiement des Progressive Web Apps',
     'Quelles sont les meilleures pratiques pour déployer une Progressive Web App sur un serveur de production ?',
     8, 3, '2024-04-19'),
    ('Les Progressive Web Apps et l\'expérience utilisateur',
     'Comment les Progressive Web Apps peuvent-elles améliorer l\'expérience utilisateur par rapport aux applications web traditionnelles ?',
     8, 4, '2024-04-20'),

    -- Posts for topic 9: serverSideRendering
    ('Les avantages du rendu côté serveur',
     'Quels sont les avantages du rendu côté serveur (SSR) par rapport au rendu côté client ?',
     9, 7, '2024-04-08'),
    ('Mise en œuvre de Server-Side Rendering avec React',
     'Comment mettre en œuvre le Server-Side Rendering avec React pour améliorer les performances et le SEO ?',
     9, 1, '2024-04-09'),
    ('Les défis du rendu côté serveur',
     'Quels sont les défis courants lors de la mise en œuvre du rendu côté serveur et comment les surmonter ?',
     9, 2, '2024-04-10'),
    ('Server-Side Rendering vs Static Site Generation',
     'Quelle est la différence entre le rendu côté serveur et la génération de sites statiques, et quand utiliser chaque méthode ?',
     9, 3, '2024-04-11'),
    ('SEO et Server-Side Rendering',
     'Comment le Server-Side Rendering améliore-t-il le SEO par rapport au rendu côté client ?',
     9, 4, '2024-04-12'),
    ('Les frameworks pour le rendu côté serveur',
     'Quels sont les meilleurs frameworks pour implémenter le Server-Side Rendering dans une application web ?',
     9, 5, '2024-04-13'),
    ('Les performances du rendu côté serveur',
     'Comment optimiser les performances de votre application utilisant le rendu côté serveur ?',
     9, 6, '2024-04-14'),
    ('Les meilleures pratiques pour le rendu côté serveur',
     'Quelles sont les meilleures pratiques pour garantir une mise en œuvre réussie du rendu côté serveur ?',
     9, 7, '2024-04-15'),
    ('Intégration du Server-Side Rendering avec les API',
     'Comment intégrer efficacement le Server-Side Rendering avec les appels API pour une expérience utilisateur fluide ?',
     9, 1, '2024-04-16'),
    ('Les outils de débogage pour le rendu côté serveur',
     'Quels outils de débogage recommandez-vous pour les applications utilisant le Server-Side Rendering ?',
     9, 2, '2024-04-17'),
    ('Les erreurs courantes dans le rendu côté serveur',
     'Quelles sont les erreurs courantes à éviter lors de la mise en œuvre du Server-Side Rendering ?',
     9, 3, '2024-04-18'),
    ('Le Server-Side Rendering et la sécurité',
     'Comment assurer la sécurité de votre application web utilisant le Server-Side Rendering ?',
     9, 4, '2024-04-19'),
    ('Server-Side Rendering et mise en cache',
     'Quelles sont les stratégies de mise en cache à adopter pour améliorer les performances du Server-Side Rendering ?',
     9, 5, '2024-04-20'),

    -- Posts for topic 10: lazyLoading
    ('Les avantages du Lazy Loading',
     'Quels sont les avantages du Lazy Loading pour les performances de votre site web ?',
     10, 3, '2024-04-08'),
    ('Implémenter le Lazy Loading des images',
     'Comment implémenter le Lazy Loading pour les images sur votre site web pour améliorer le temps de chargement ?',
     10, 4, '2024-04-09'),
    ('Lazy Loading des composants dans React',
     'Comment utiliser le Lazy Loading pour les composants React afin d\'optimiser les performances ?',
     10, 5, '2024-04-10'),
    ('Lazy Loading et SEO',
     'Comment s\'assurer que le Lazy Loading n\'affecte pas négativement le SEO de votre site web ?',
     10, 6, '2024-04-11'),
    ('Les meilleures pratiques pour le Lazy Loading',
     'Quelles sont les meilleures pratiques pour implémenter efficacement le Lazy Loading dans vos projets web ?',
     10, 7, '2024-04-12'),
    ('Lazy Loading des vidéos',
     'Comment implémenter le Lazy Loading pour les vidéos sur votre site web pour améliorer les performances ?',
     10, 1, '2024-04-13'),
    ('Les outils et bibliothèques pour le Lazy Loading',
     'Quels outils et bibliothèques recommandez-vous pour faciliter l\'implémentation du Lazy Loading ?',
     10, 2, '2024-04-14'),
    ('Lazy Loading et compatibilité des navigateurs',
     'Comment gérer la compatibilité des navigateurs lors de l\'implémentation du Lazy Loading ?',
     10, 3, '2024-04-15'),
    ('Lazy Loading pour les sections de page',
     'Comment implémenter le Lazy Loading pour différentes sections de votre page web pour améliorer l\'expérience utilisateur ?',
     10, 4, '2024-04-16'),
    ('Les erreurs courantes dans le Lazy Loading',
     'Quelles sont les erreurs courantes à éviter lors de l\'implémentation du Lazy Loading ?',
     10, 5, '2024-04-17'),
    ('Les avantages du Lazy Loading pour les applications mobiles',
     'Comment le Lazy Loading peut-il améliorer les performances des applications mobiles ?',
     10, 6, '2024-04-18'),
    ('Lazy Loading pour les frameworks JavaScript',
     'Comment implémenter le Lazy Loading dans différents frameworks JavaScript (Vue, Angular, Svelte) ?',
     10, 7, '2024-04-19'),
    ('Lazy Loading et expérience utilisateur',
     'Comment le Lazy Loading peut-il améliorer l\'expérience utilisateur sur les sites web à contenu lourd ?',
     10, 1, '2024-04-20'),
    ('Lazy Loading des polices de caractères',
     'Comment implémenter le Lazy Loading pour les polices de caractères sur votre site web pour optimiser les performances ?',
     10, 2, '2024-04-21'),
    ('Lazy Loading et accessibilité',
     'Comment s\'assurer que le Lazy Loading n\'affecte pas négativement l\'accessibilité de votre site web ?',
     10, 3, '2024-04-22');