INSERT INTO posts (Title, Content, Id_topics, Id_User, Create_post)
VALUES ('Faut mieux faire un carrousel en natif ou avec bibliothèque ?',
        'Je suis en train de faire une boutique en js et je veux faire un carrousel pour afficher mes articles et j\'essaye de bien opti mon code donc je ne sais pas si je dois me faciliter la vie en utilisant swiper par exemple mais donc importer toutes une bibliothèque où me complexifier la vie en créant ma fonction qui fait le carrousel ',
        1, 1, '2024-04-03'),
       ('Site audi',
        'je cherche a faire une replique du site audi afin de m\'entrainer mais je sais pas faire de caroussel pouvez vous me dire comment faire svp',
        2, 1, '2024-04-04'),
       ('site mobile',
        'bonjour je cherche a rendre mon site responsive sur un style de format iphone 14 mais je ne sais pas comment faire',
        1, 3, '2024-04-05'),
       ('Problème de performance avec animations CSS',
        'Salut à tous, j\'ai intégré des animations CSS sur mon site, mais cela cause des ralentissements importants. Avez-vous des astuces pour optimiser les performances ?',
        1, 3, '2024-04-06'),
       ('Choix de framework JS',
        'Je dois démarrer un nouveau projet web et je me demande quel framework JS serait le plus adapté entre React, Vue et Angular. Des conseils ?',
        1, 2, '2024-04-07'),
       ('Problème d\'alignement en Flexbox',
        'Bonjour, j\'ai un souci avec l\'alignement de mes éléments en utilisant Flexbox. Ils ne s\'alignent pas comme je le souhaite. Des idées ?',
        1, 1, '2024-04-08'),
       ('Intégration de Stripe pour paiements',
        'Bonjour, je suis en train de mettre en place un système de paiement pour mon site web et j\'aimerais savoir comment intégrer Stripe correctement.',
        1, 3, '2024-04-09'),
       ('Utilisation des SVG pour des icônes',
        'Salut, est-il préférable d\'utiliser des fichiers SVG pour mes icônes ou bien de continuer avec des polices d\'icônes comme FontAwesome ?',
        1, 2, '2024-04-10'),
       ('Problème de compatibilité IE11',
        'Je rencontre des problèmes de compatibilité avec Internet Explorer 11 sur mon site. Y a-t-il des solutions pour corriger cela sans trop de modifications ?',
        1, 2, '2024-04-11'),
       ('Optimisation SEO pour un blog',
        'Bonjour, je souhaite optimiser le SEO de mon blog afin d\'améliorer mon classement sur les moteurs de recherche. Quelles sont les meilleures pratiques à suivre ?',
        1, 3, '2024-04-12'),
       ('Débogage d\'une application Node.js',
        'Bonjour, je rencontre des difficultés pour déboguer mon application Node.js. Avez-vous des outils ou des techniques à recommander ?',
        1, 2, '2024-04-13'),
       ('Création d\'un formulaire de contact',
        'Salut à tous, je dois créer un formulaire de contact pour mon site. Quelle est la meilleure façon de le sécuriser contre les spams ?',
        2, 1, '2024-04-14'),

       ('Animation de navigation sur une page unique',
        'Bonjour, je voudrais ajouter des animations de navigation entre les sections de ma page unique. Quel serait le meilleur moyen d\'y parvenir ?',
        1, 2, '2024-04-15'),

       ('Problèmes de CORS avec une API externe',
        'Je suis en train de développer une application web et je rencontre des problèmes de CORS en essayant de récupérer des données d\'une API externe. Comment puis-je résoudre cela ?',
        1, 3, '2024-04-16'),

       ('Choix d\'un CMS pour un blog',
        'Je souhaite lancer un blog et je ne sais pas quel CMS choisir entre WordPress, Ghost et Joomla. Avez-vous des recommandations ?',
        2, 1, '2024-04-17'),

       ('Intégration d\'une carte interactive',
        'Salut, je veux intégrer une carte interactive sur mon site web pour afficher des points d\'intérêt. Quelle bibliothèque recommandez-vous pour cela ?',
        1, 2, '2024-04-18'),

       ('Configuration de webpack pour un projet React',
        'Je démarre un projet avec React et je dois configurer webpack. Quels sont les points clés à ne pas manquer dans cette configuration ?',
        1, 3, '2024-04-19'),

       ('Problème avec les cookies en JavaScript',
        'Bonjour, je rencontre des difficultés pour gérer les cookies en JavaScript sur mon site. Quelqu\'un peut-il m\'aider à comprendre comment cela fonctionne ?',
        2, 2, '2024-04-20'),

       ('Utilisation de SASS pour le styling',
        'Salut, je commence à utiliser SASS pour styliser mon site web. Avez-vous des astuces ou des bonnes pratiques à partager ?',
        1, 1, '2024-04-21'),

       ('Mise en place d\'un déploiement continu',
        'Je veux mettre en place un système de déploiement continu pour mon application web. Quels outils et services recommandez-vous ?',
        1, 3, '2024-04-22'),

       ('Accessibilité des sites web',
        'Bonjour, je veux rendre mon site web plus accessible. Quelles sont les meilleures pratiques à suivre pour y parvenir ?',
        2, 1, '2024-04-23'),

       ('Utilisation d\'API REST vs GraphQL',
        'Je dois choisir entre utiliser une API REST et GraphQL pour mon projet. Quels sont les avantages et les inconvénients de chaque approche ?',
        1, 2, '2024-04-24'),

       ('Création d\'une application PWA',
        'Salut, je suis intéressé par la création d\'une Progressive Web App (PWA) pour mon site. Quels sont les premiers pas à suivre ?',
        2, 3, '2024-04-25'),

       ('Problème de cache avec Service Workers',
        'Bonjour, j\'ai un problème avec le cache de mes Service Workers sur ma PWA. Les mises à jour ne sont pas prises en compte. Des idées ?',
        1, 2, '2024-04-26'),

       ('Optimisation des images pour le web',
        'Je cherche à optimiser les images sur mon site web pour améliorer les temps de chargement. Quels formats et techniques recommandez-vous ?',
        1, 1, '2024-04-27'),

       ('Intégration de Google Analytics',
        'Salut, je veux intégrer Google Analytics à mon site web pour suivre les statistiques de mes visiteurs. Quelle est la meilleure façon de le faire ?',
        1, 3, '2024-04-28'),

       ('Mise en place d\'une architecture microservices',
        'Bonjour, je dois mettre en place une architecture microservices pour mon application. Quels sont les principaux défis et comment les surmonter ?',
        2, 2, '2024-04-29'),

       ('Utilisation de WebSockets pour la communication en temps réel',
        'Je veux implémenter des fonctionnalités de communication en temps réel sur mon site en utilisant WebSockets. Avez-vous des exemples ou des ressources pour m\'aider à démarrer ?',
        1, 1, '2024-04-30'),

       ('Gestion des erreurs en JavaScript',
        'Salut, je veux améliorer la gestion des erreurs dans mon code JavaScript. Quelles sont les meilleures pratiques pour cela ?',
        2, 2, '2024-05-01'),

       ('Déploiement d\'une application sur AWS',
        'Bonjour, je souhaite déployer mon application web sur AWS. Quels services AWS dois-je utiliser et quelles sont les étapes à suivre ?',
        1, 3, '2024-05-02'),

       ('Utilisation des Web Components',
        'Salut, je m\'intéresse aux Web Components pour construire des éléments réutilisables sur mon site. Comment commencer avec cette technologie ?',
        1, 1, '2024-05-03');